### ISSUE TITLE
How to check if ALL files are updated in a directory ?

### ISSUE THREAD

**Issue by sboulianne** [thehunmonkgroup/nagios-plugin-newest-file-age#7]
Hi,

I use this plugin to monitor our backups and I like it!
Thanks you very much for sharing.

I have a little question, how to check if ALL files are updated in a directory ?

Thanks again for your support.

Sébastien.

**Comment by thehunmonkgroup** [comment]
https://github.com/thehunmonkgroup/nagios-plugin-file-ages-in-dirs
