### ISSUE TITLE
Alert when no files in directory

### ISSUE THREAD

**Issue by kurtabersold** [thehunmonkgroup/nagios-plugin-newest-file-age#8]
If there are no files in the specified directory, check_newest_file_age still exits OK. Is this behavior intended? I think if there are no files it should exit UNKNOWN, but maybe I don't fully understand the intent of this plugin.

Sample output:

```
$ ./check_newest_file_age -d /tmp/test
OK: 1/1 -- /tmp/test: No files
```

**Comment by thehunmonkgroup** [comment]
Use the -W or -C args if you want different behavior in the no files case.
